
# Define services
services:
  # App backend service
  app:
    # Configuration for building the docker image for the backend service
    build:
      context: . # Use an image built from the specified dockerfile in the `springboot-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # Forward the exposed port 4000 on the container to port 4000 on the host machine
    restart: always
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

# Networks to be created to facilitate communication between containers
networks:
    backend: 
      